### ISSUE TITLE
AnimalAi.exe crashes

### ISSUE THREAD

**Issue by bastiankayser** [beyretb/AnimalAI-Olympics#31] opened 2019-07-02 12:14 UTC
Installation in virtualenv with
pip install animalai
and 
pip install animalai-train
worked without a problem.
However, when I try to start the AnimalAi.exe in /env, the following error message appears:
![animalOlympics_error](https://user-images.githubusercontent.com/3287187/60511955-8ed70700-9cd3-11e9-9a89-b8cc47f69068.png)

Env:
Windows 10 Pro 1903
Python 3.6.3

**Comment by beyretb** [comment] 2019-07-02 12:24
Hello,

I'm going to need a bit more details as it works just fine on our side:

- did you dowload the [last version](https://www.doc.ic.ac.uk/~bb1010/animalAI/env_windows_v1.0.0.zip)?
- how are you running the environment: from python or you just double click on the .exe?
- did you extract all the files in one folder or just the .exe file?
- can you give us more details about your configuration (CPU, GPU, drivers you're using)?

Thanks

**Comment by bastiankayser** [comment] 2019-07-02 12:37
Hi,

- yes downloaded last version
- tried both: double click on AnimalAi.exe and python visualizeArena.py configs/exampleConfig.yaml both show same error
- I extracted all the files into env/ as described in the installation guide
- System Info:
Intel i7-7700HQ 4 Cores
NVIDIA Geforce GTX 1050Ti
Geforce drivers 26.21.14.3086 from 5/22/2019

Thanks.

**Comment by beyretb** [comment] 2019-07-02 13:46
Your windows version is 64 bits right?

I cannot reproduce your error unfortunately (tried on several windows machines), it seems to come from your config. Running the environment alone, without installing any python packages, should work (there are no direct dependencies).

This is most likely due to your visual c++ libraries specifically, we can't be 100% sure however. I would recommend looking at [this page](https://www.howtogeek.com/256245/why-are-there-so-many-microsoft-visual-c-redistributables-installed-on-my-pc/) and [this one](https://www.kapilarya.com/this-application-has-requested-the-runtime-to-terminate-it-in-an-unusual-way-windows-10) if you would like to install the latest version (at your own risk though).

Please let us know the outcome if you attempt these steps.

**Comment by bastiankayser** [comment] 2019-07-02 18:40
Yes 64 bit Windows
The c++ libraries were NOT the problem, at least different reinstalls did not solve the problem.
What DID solve the problem was to right click on AnimalAi.exe -> Run with graphics processor -> Integrated graphics (default).
So the interaction with my geforce card seems to be the problem, eventhough now I did not have this issue before with any other program.

**Comment by beyretb** [comment] 2019-07-02 22:04
Hi, glad you sorted out this issue and thank you for posting the solution.
Closing the issue as it is solved.

**Closed by beyretb** 2019-07-02 22:04 UTC
Labels: bug
