### ISSUE TITLE
Dockerfile submission error using proxy

### ISSUE THREAD

**Issue by Bonum** [beyretb/AnimalAI-Olympics#50] opened 2019-07-24 10:49 UTC
I am trying to make a submission on Windows with docker settings for proxy:
export "HTTP_PROXY=http://proxy.xxx:8080" and "HTTPS_PROXY=http://proxy.xxx:8080"

AnimalAI-Olympics\examples\submission>docker build --tag=submission .

Only first step was executed (downloaded) successfully :
 FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
Here is the log:

AnimalAI-Olympics\examples\submission>docker build --tag=submission .
Sending build context to Docker daemon  29.88MB
Step 1/20 : FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04
 ---> fa42893c355d
Step 2/20 : RUN apt-get clean && apt-get update && apt-get install -y locales
 ---> Running in 827ac1f47f87
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
  Failed to connect to developer.download.nvidia.com port 443: Connection refused
Err:2 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
  Failed to connect to developer.download.nvidia.com port 443: Connection refused
Err:3 http://archive.ubuntu.com/ubuntu xenial InRelease
  Could not connect to archive.ubuntu.com:80 (91.189.88.162). - connect (111: Connection refused) [IP: 91.189.88.162 80]
Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.162 80]
Err:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.162 80]
Err:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Could not connect to security.ubuntu.com:80 (91.189.88.24). - connect (111: Connection refused) [IP: 91.189.88.24 80]
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.162). - connect (111: Connecti
on refused) [IP: 91.189.88.162 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.162 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.162 80]
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Could not connect to security.ubuntu.com:80 (91.189.88.24). - connect (111
: Connection refused) [IP: 91.189.88.24 80]
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/InRelease  Failed to connect to developer.download.nvidia.com port
 443: Connection refused
W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64/InRelease  Failed to connect to developer.download.nvi
dia.com port 443: Connection refused
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package locales is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'locales' has no installation candidate
The command '/bin/sh -c apt-get clean && apt-get update && apt-get install -y locales' returned a non-zero code: 100

**Comment by beyretb** [comment] 2019-07-24 14:34
Hi,

This is a docker related issue, you clearly seem to have connectivity problems as your build isn't connecting to any of the repositories, which might be related to your proxy setup. We don't have the resources to support custom configurations unfortunately, I can only recommend asking the docker community for help on this.

**Comment by Bonum** [comment] 2019-07-24 14:51
Hi, 

I agree that this is a docker related issue and you don't have to support custom configurations.

Just to mention:
*    My docker has connection : 
    Step 1/20  : FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04 ---> fa42893c355d
          was downloaded successfully
    Something wrong is going at 
     Step 2/20 : RUN apt-get clean && apt-get update && apt-get install -y locales
    Actually I split this in three steps and the first passed.

* Without a docker I cannot participate in your competition.

**Comment by beyretb** [comment] 2019-07-24 15:03
> I agree that this is a docker related issue and you don't have to support custom configurations

We are more than happy to provide all the help we can when we are able to reproduce an issue, which is not the case here unfortunately

> My docker has connection 

It has some connection but I think your proxy does not work for some crucial services such as the ubuntu and nvidia repositories.

Not sure if this can help you but did you try [this](https://dev.to/zyfa/setup-the-proxy-for-dockerfile-building--4jc8) ?

**Comment by krisives** [comment] 2019-07-24 18:14
>  Actually I split this in three steps and the first passed.

That's because `apt clean` doesn't do anything related to networking. `apt-get update` will contact the repositories configured for your Docker container and `apt install` will fetch packages from the repositories.

It fails because:

```
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 InRelease
Failed to connect to developer.download.nvidia.com port 443: Connection refused
```

Your HTTP proxy isn't allowing HTTPS connections to `developer.download.nvidia.com` on port 443.

It also appears your proxy is not configured correctly for regular HTTP connections either:

```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease Unable to connect to archive.ubuntu.com:http: [IP: 91.189.88.162 80]
```

> Without a docker I cannot participate in your competition.

Docker really has very little to do with this problem. Your HTTP proxy is the problem. You'll probably find the same problem with any program/command that attempts to use your proxy:

```
export http_proxy=http://proxy.xxx:8080/
curl https://github.com
```

**Comment by Bonum** [comment] 2019-07-25 10:40
Hello Benjamin and Kristopher,

Thank you for your effort to resolve my problem.

In fact my docker is properly configured with proxy settings and has connection to outside, but running 
the first line of Dockerfile caused for some reason problems with http_proxy settings.

The solution is to add also INSIDE Dockerfile after the first line:
```
ENV http_proxy "http://proxy.xxx:8080"
ENV https_proxy "http://proxy.xxx:8080"
```

Now "docker build --tag=submission . " was executed without a problem ( it took a while to install all dependencies).

Please have in mind that you set

 `ENV http_proxy ""` etc. before 
```
# YOUR COMMANDS GO HERE
RUN pip install animalai-train
```
which caused a problem. 
Deleting http_proxy settings should be moved after that.

Regards,
Bonum

**Comment by beyretb** [comment] 2019-07-28 08:35
glad you could find a fix! closing this issue

**Closed by beyretb** 2019-07-28 08:35 UTC
